name: checkov-scan
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:

jobs:
  call-checkov-scan-workflow:
    permissions:
      # If code_scanning_enabled is true
      security-events: write
      actions: read

      # If code_scanning_enabled is false
      # checks: write

      # General
      contents: read
    uses: christosgalano/Workflow-Templates/.github/workflows/checkov_scan.yaml@main
    with:
      template_dir: bicep
      template_prefix: azure.deploy
      code_scanning_enabled: true
      enable_harder_runner: false
