name: destroy-infra
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      rg_name:
        description: "Specify resource group name"
        required: true
        type: string

jobs:
  approve:
    name: Approve infrastructure teardown
    permissions:
      issues: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1,user2,...
          minimum-approvals: N
          issue-title: "Destroying infrastructure"
          exclude-workflow-initiator-as-approver: false

  call-azure-destroy-workflow:
    uses: christosgalano/Workflow-Templates/.github/workflows/azure_destroy.yaml@main
    needs: approve
    with:
      rg_name: ${{ inputs.rg_name }}
      enable_harder_runner: false
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
