# This workflows deletes the runs of all the workflows in a repository.
name: delete-workflow-runs
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      owner:
        description: "Specify repository owner"
        required: true
      repo:
        description: "Specify repository"
        required: true
      token:
        description: "Specify GitHub Personal Access Token"
        default: ${{ github.token }}
        required: true

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: christosgalano/Workflows-Actions-Library/.github/actions/delete-workflow-runs@main
        with:
          owner: ${{ inputs.owner }}
          repo: ${{ inputs.repo }}
          token: ${{ secrets.GITHUB_PAT }}
