# This workflows gets the latest run status of a specified workflow.
name: workflow-run-status
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      workflow:
        type: string
        required: true
        description: "Name or ID of the workflow."

permissions:
  actions: read
  contents: read

jobs:
  workflow-run-status:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Get repository's name
        id: get-repo-name
        run: |
          repo_name="$(cut -d '/' -f 2 <<< "${{ github.repository }}" )";
          echo "repo-name=$repo_name" >> $GITHUB_OUTPUT

      # Workflow must belong in this repository since we use the GITHUB_TOKEN.
      # If you wish to poll the latest run of a workflow that resides in another repository,
      # then create a secret containing a GitHUb PAT with the necessary permissions and use that one.
      - name: Get workflow's latest run status
        uses: christosgalano/Workflows-Actions-Library/.github/actions/workflow-run-status@main
        id: get-run-status
        with:
          workflow: ${{ inputs.workflow }}
          owner: ${{ github.repository_owner }}
          repository: ${{ steps.get-repo-name.outputs.repo-name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print workflow's latest run status
        run: echo ${{ steps.get-run-status.outputs.workflow-run-status }}
