name: "Create/Update Label"
author: "Christos Galanopoulos"
description: "Create or update a label in all of the user's repositories"
inputs:
  name:
    description: "Specify label name"
    required: true
  color:
    description: "Specify label color"
    required: true
  description:
    description: "Specify label description"
    required: true
  token:
    description: "Specify GitHub Personal Access Token"
    required: true
branding:
  icon: edit-2
  color: gray-dark
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        NAME: ${{ inputs.name }}
        COLOR: ${{ inputs.color }}
        DESCRIPTION: ${{ inputs.description }}
        TOKEN: ${{ inputs.token }}
      run: |
        ${{ github.action_path }}/create_update_label.sh \
          -n ${{ env.NAME }} \
          -c ${{ env.COLOR }} \
          -d ${{ env.DESCRIPTION }} \
          -t ${{ env.TOKEN }}
